### ISSUE TITLE
<Android>How to communicate with Java/AAR

### ISSUE THREAD

**Issue by FanEric** [StereoKit/StereoKit#1045]
I'm working on an Android project with StereoKit, is there any sample about how to communicate with Android AAR? Thanks.

**Comment by maluoi** [comment]
This is less of a StereoKit thing, and more of a C# general thing! C# does have some pretty great tools for working with Java projects, like auto-generating C# idiomatic bindings for [JARs and AARs](https://learn.microsoft.com/en-us/dotnet/android/building-apps/build-items#androidlibrary), compiling [.java files _in your C# project_](https://learn.microsoft.com/en-us/dotnet/android/building-apps/build-items#androidjavasource), and pretty much the full [Android API](https://learn.microsoft.com/en-us/dotnet/api/?preserve-view=true&view=net-android-34.0) accessible as part of the standard API for Android targeted projects.

Because of the native support for the Android APIs, I've seen a few projects just dropping their Android .aar/.jar plugins because they could just be done natively in C#.

StereoKit's multi template for C# does have _some_ additional tools for Android, but this is mostly just the fact that any code files ending with `.Android.cs` will only be compiled when building the Android target. This can be useful, but I still pretty frequently use `#if ANDROID` in normal files for Android specific stuff.
