### ISSUE TITLE
Add a method for changing the origin

### ISSUE THREAD

**Issue by maluoi** [StereoKit/StereoKit#189]
Related to #184

This may be as simple as updating xr_app_space to have a new offset, but this may also have snowball effects on systems that rely on xr_app_space, and may also need updated when the offset is changed.

**Comment by austinbhale** [comment]
On the HoloLens 2, whenever StereoKit loses tracking by covering the inertial sensors, any rendered elements in the world will readjust to the new tracking space. To prevent this drift in our application, we make use of the StationaryFrameOfReference and spatial anchors to render holograms. However, it'd be very convenient to set the StereoKit origin ourselves to this frame of reference, otherwise we'd have to track all spatial offsets in an app session. We have a scenario similar to the docs, where customers will move outside the 5 meter space (https://learn.microsoft.com/en-us/windows/mixed-reality/design/spatial-anchors#render-highly-dynamic-holograms-using-the-stationary-frame-of-reference-instead-of-a-local-spatial-anchor).

Let me know how I can help! I plan on diving into StereoKit to see what this might require.

**Comment by maluoi** [comment]
Adding some notes from [where this issue is referenced in /psi](https://github.com/microsoft/psi/blob/35cb04ce24569677d3a8da0216e9450e66cbbd83/Sources/MixedReality/Microsoft.Psi.MixedReality.UniversalWindows/MixedReality.cs#L146) for reference.

>  TODO: It would be nice if we could actually just shift the origin coordinate system in StereoKit to the pose currently defined in StereoKitTransforms.WorldPose. There's currently an open issue for this: https://github.com/maluoi/StereoKit/issues/189
>
> Simply setting the renderer camera root does not work, as its transform appears to be applied in the wrong order. E.g., if the starting StereoKit pose is at a yaw rotation of 180 degrees, we would want to apply that transform first, then apply the transform of the headset pose (perhaps pitching up). Instead, it appears that the headset pose is applied first (e.g., pitching up), and *then* the Renderer.CameraRoot transform is applied (yaw of 180 degrees) which in this example manifests as the pitch going down, opposite of what we desired.

**Comment by maluoi** [comment]
This is now [`World.OriginMode`](https://stereokit.net/Pages/StereoKit/World/OriginMode.html) and [`World.OriginOffset`](https://stereokit.net/Pages/StereoKit/World/OriginOffset.html), also [`SKSetting.origin`](https://stereokit.net/Pages/StereoKit/SKSettings/origin.html)
