### ISSUE TITLE
Remote rendering on PC with StereoKit

### ISSUE THREAD

**Issue by xiaolongrenlzj** [StereoKit/StereoKit#225]
Hi Nick,

Dose StereoKit support remote rendering on PC? I am wondering if I can use a PC to render the frames and send them back to HoloLens. It's kind of like Holographic remoting. 

Thanks a lot.

**Comment by maluoi** [comment]
StereoKit doesn't directly support this yet! It should be possible to integrate the holographic remoting sdk in some format or another, but I've not tried that.

If you're interested in this from the development iteration time perspective, I think you'll be pleased at how fast SK is already! One big thing I focus on, is ensuring StereoKit builds fast enough that deploying to device takes _very_ little time. But if your interest is in offloading slow rendering to a PC, that'll be a lot of work just yet.

**Comment by IanET** [comment]
Fwiw, +1 for supporting Holographic Remoting. I also have a few scenarios that exceed the rendering capacity of the HoloLens so currently use Unity HAR and C++ HAR depending on the situation. Both work fine to a point but StereoKit support would be great!

**Comment by maluoi** [comment]
Thanks for the +1 here! Are you primarily interested in something where the PC does 100% of the compute, like straight up with the Holographic Remoting Player? Or are you looking for a little more control, like a custom remoting player shell, or possibly mixing local and remote rendering?

For the record, I don't _think_ I'll be able to prioritize this particularly soon, I currently have a lot of features in the queue right now. But, @IanET, if you want to hit me up internally on Teams with your use case, there's certainly a chance you could change my mind :)

**Comment by IanET** [comment]
My use-case is 100% PC based but I can use Unity etc for now so don't prioritize this over other features requests. I just wanted to register my support for this :)

**Comment by maluoi** [comment]
A small update on this, I now have remoting working on `/develop`, and the next preview build of StereoKit should work with this codebase over here:
https://github.com/StereoKit/StereoKit.HolographicRemoting

My plan for v0.3.7 is to add `StereoKit.HolographicRemoting` as a separate NuGet package, with a `HolographicRemoting` `IStepper` that will enable remoting when added to a StereoKit project :)

**Comment by maluoi** [comment]
v0.3.7-preview.2 isn't out _quite_ yet, but should be in a day or two! You can get preview builds from the NuGet package manager when you enable the "Include prerelease" checkbox.

This current integration is meant for the HL2 Remoting Player, nothing really more complicated than that here. This was actually pretty straightforward, as it basically just swaps out the active OpenXR runtime for the Remoting OpenXR runtime, and it just works. So I imagine this is _not_ the route I'd take if I was trying to mix local and remote content. That's still very much a separate thing from this.

**Comment by laultman** [comment]
I tried the preview check box. Seems to be some issue with the version numbers. In VS nuget package manager says it's installed but the build clearly thinks otherwise.

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1102	Unable to find package StereoKit with version (>= 0.3.7-preview.2)
  - Found 88 version(s) in nuget.org [ Nearest version: 0.3.7-preview.1 ]
  - Found 1 version(s) in StereoKit [ Nearest version: 0.3.5 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages	StereoKitRemoting	C:\Users\JLarryAultman\source\SKHolographicRemoting\StereoKitRemoting\StereoKitRemoting.csproj	1

**Comment by maluoi** [comment]
That is correct, v0.3.7-preview.2 isn't out quite yet, v0.3.7-preview.1 is still latest. Hang on a day or two and I'll have that up :)

**Comment by maluoi** [comment]
v0.3.7-preview.2 is up now, that repository should start working! I'll be working on the Holographic Remoting package a bunch more next week, so the experience will be better then.

**Comment by laultman** [comment]
Awesome! Got it. Works like a charm. Can't wait for your enhancements. You're the best!
In the meantime, I will be hacking away at it myself.

**Comment by laultman** [comment]
Had some issues with the Console configuration. Got that cleared up. If you have an error: System.DllNotFoundException: 'Unable to load DLL 'StereoKitC' or one of its dependencies.
It is most likely your SK.Initialize(settings) call. See my solution [here](https://github.com/StereoKit/StereoKit.HolographicRemoting/issues/1).

**Comment by laultman** [comment]
Question, do you think StereoKit performance might be improved at the CPU level by moving up one notch to .NET Standard 2.1? I like a lot of the runtime implementations reducing the number of Nuget packages, but mostly, I like the SIMD opportunity for Vectors. When dealing with lots of objects in collections the Span<T> could be very useful/efficient for managing the objects in scenes.
Also, it's not like .NET Standard 2.1 is new, it's been around since 2018.
Here are some links to look at.
[1 ](https://devblogs.microsoft.com/dotnet/the-jit-finally-proposed-jit-and-simd-are-getting-married/)
[2 ](https://docs.microsoft.com/en-us/archive/msdn-magazine/2018/january/csharp-all-about-span-exploring-a-new-net-mainstay)
I do understand that it's a lot of effort to go back and optimize the code. I also know that adding features is very important. Topic for discussion?

**Comment by maluoi** [comment]
Moving StereoKit to .NET Standard 2.1 would prevent compatibility with UWP/HoloLens unfortunately, so it's mostly off the table. Now that UWP is deprecated, it's not getting any improvements, so it's frozen on .NET Standard 2.0!

However, some relevant tidbits here!
- StereoKit does use `System.Numerics` under the hood for math types in C#, which already benefits from a SIMD implementation.
- StereoKit's C# wrapper is very thin, so there's really not much C# code for StereoKit to optimize. Performance critical code is 100% C/C++.
- StereoKit using .NET Standard 2.0 is just for compatibility! Your own project or extension can use 2.1, or even a more explicit flavor with additional performance options like .NET 6/7, depending on what your platform requirements end up being.

Personally, I'm mostly interested in .NET Standard 2.1 due to some improved tools for marshaling between C and C#! Maybe someday :)

Also FYI, since this is off-topic for _this_ thread, it may be better to create a separate Discussion thread next time!

**Comment by TopperDEL** [comment]
Just for my understanding: calling into a net standard 2.0 dll from net 6 would still use the latest optimisation from net 6 where applicable, right?

**Comment by maluoi** [comment]
As I understand it, .NET standard is kinda like a C# `interface` that passes through to an underlying .NET runtime, so to some extent yes! However, if you're hoping that StereoKit can use stuff like `Span<>` as part of its API for performance considerations, that's a 2.1 only sort of thing. And I _think_ that's more what the question here was about? :)

**Comment by TopperDEL** [comment]
No, I was mainly shooting at the base optimisation of net. That spans are not involved was clear to me. 😊
