### ISSUE TITLE
Docs: Consider documenting / explicit mention of the effect of multiplying a bounds with a float

### ISSUE THREAD

**Issue by Strepto** [StereoKit/StereoKit#349]
https://github.com/maluoi/StereoKit/blob/dcd95fdfe6bbbd89e2d33ad7c628d97491ad5213/StereoKit/Math/Bounds.cs#L104

This scales the bounds by the given amount, but its not documented with XML or [website](https://stereokit.net/Pages/Reference/Bounds.html). I had to check the source for the definition of what the operator did. 

Usecase: 
I was looking for a scale method to use in the example below, but could not find anything before I found the undocumented multiplier by chance. I tried multiplying with a Vec3 at first, but that did not work. I only kept looking for this instead of fixing my own since most things have a nice intuitive solution in SK ✨ 

```cs
        var scale = 0.1f;
        UI.Handle("1", ref cubePose, Mesh.Cube.Bounds * scale );
        Mesh.Cube.Draw(Material.Default, cubePose.ToMatrix(scale));
```

I would maybe consider a `bounds.WithScale(float scale) -> new scaled bounds` to make it more discoverable that such a method exits, and/or add a xml doc for the existing operator. Also a non-uniform scaling by a Vec3 could maybe be useful, but not needed by me.

Let me know if you want a contribution for this.

**Comment by maluoi** [comment]
Yeah, these are indeed excellent ideas! Adding some methods for this would definitely be a great route for operator discovery :) The current naming convention for this type of thing in StereoKit is `Scale` for self modification, and `Scaled` for returning a modified value (See `Vec3.Normalize` and `Vec3.Normalized`).

Documenting the operator overload would also be really good! One reason I haven't done this yet (for any operators, actually!) is because StereoKit's documenter does not yet support operator overloads, so this is something that needs to be implemented.

If you wanted to write `Scale` and `Scaled` methods with variants+operator for non-uniform, I'd definitely be grateful :) Should probably skip on commentdocs for the operators until SK's documenter supports it properly though, I'll try and implement that soon.
