### ISSUE TITLE
SKDesktopDuplicator

### ISSUE THREAD

**Issue by juntao-huang** [StereoKit/StereoKit#441]
<img width="446" alt="搜狗截图20220726114339" src="https://user-images.githubusercontent.com/66586670/180918427-5bea556f-c176-447e-a646-af7d64fcbca8.png">
Compile time Bug：[SK diagnostic] platform_read_file can't find DesktopDuplicator.ini

How can I solve this problem? Thank you (I'm new to programming)

**Comment by maluoi** [comment]
Ah, this might actually be an outdated version of the passthrough extension code! The `xrEndFrame` issue is there because passthrough isn't available, or some related thing. Make sure you have passthrough enabled in the Oculus beta settings!

![image](https://user-images.githubusercontent.com/8484884/180919583-f8945a21-6247-4217-86cd-f26552b11001.png)

I'll also update the passthrough script in a moment, but that'll just ensure that the app continues properly without any passthrough.

**Comment by juntao-huang** [comment]
Thanks for the quick answer
