### ISSUE TITLE
Thread-safe Stepper add/remove

### ISSUE THREAD

**Issue by maluoi** [StereoKit/StereoKit#538]
Adding and removing `IStepper`s from a separate thread can cause issues. Here's a small repro case where `Step` will sometimes get called after `Shutdown`. Some initial discussion and related work happened in #528.

```csharp
using StereoKit;
using StereoKit.Framework;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

SK.Initialize("Stepper Stress Test");

Task.Run(() => {
	Random r = new Random();
	List<StepperTest> steppers = new List<StepperTest>();
	while (true)
	{
		for (int i = 0; i < 10000; i++)
			steppers.Add(SK.AddStepper<StepperTest>());

		for (int i = 0; i < 10000; i++)
			steppers.RemoveAt(r.Next(steppers.Count));
	}
});

SK.Run(() => {
	Mesh.Sphere.Draw(Material.Default, Matrix.TS(0, 0, -0.5f, 0.1f));
});

class StepperTest : IStepper
{
	private Model model;
	public  bool  Enabled => true;

	public bool Initialize()
	{
		Model m = new Model();
		return true;
	}
	public void Shutdown() => model = null;
	public void Step    () => model.Draw(Matrix.Identity);
}
```

One proposal was to shift the stepper list over to a `ConcurrentDictionary` (maybe `ConcurrentBag`?). Another possibility could be some separate structure that's added to from parallel threads, then executed at a specific moment on the main thread.

**Comment by austinbhale** [comment]
I started some work on this issue here https://github.com/StereoKit/StereoKit/compare/develop...austinbhale:StereoKit:develop and found that using a `BlockingCollection` to protect access to the list kept most of the expected Steppers functionality when being added/removed/stepped through.

---
The other Concurrent classes were very tricky to implement in this scenario:

### ConcurrentStack / ConcurrentBag / ConcurrentQueue
Removing a specific element from a bag or stack requires you to take items out of the collection and put them back in again. The `GetEnumerable` method creates a snapshot in time, so anything modified in the collection is not seen (https://learn.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentbag-1.getenumerator?redirectedfrom=MSDN&view=net-7.0#remarks). If you were to iterate over this collection in `Step`, and a `Shutdown` was called for an item, the stepper will still call its own `Step` after a `Shutdown` call.

### ConcurrentDictionary
It's difficult to find a unique key for ISteppers without adding a GUID property or alternative, which would break their current contract. Also the `GetHashCode` cannot be used as a key for instances of Steppers (https://learn.microsoft.com/en-us/dotnet/api/system.object.gethashcode?redirectedfrom=MSDN&view=net-7.0#remarks). It's also interesting to note that adding IStepper (or any object) instances with the same hash code can be used as separate dictionary keys. Not sure how long that would hold until a collision though. One time I tried to have a lock as a value for each IStepper instance so that I could sorta replicate a fine-grained synchronization, but that would probably need careful additions to avoid deadlocks.

### BlockingCollection with List
The `BlockingCollection` acts like a lock for the list, but it safely preserves the order of who's accessing the list via Add/Remove/Step. It also just adds/takes the reference to the list, instead of copying it each time. The biggest drawback of the current code is that it may hang on Step for longer Initialize/Shutdown methods. It's great if nothing hangs on Step() and instead modify it to be a nonblocking TryTake. I'm concerned about not seeing any steppers if the TryTake immediately returns false due to it being in use by the Add/Remove methods. Curious about a solution that could do this.

---

In sum, I like the idea of a solution that somehow uses the Concurrent class, and maybe some flipping of pointers for the Interlocked, so that the locking is taken care of. I added your test for this too :) What do you think of this approach?

**Comment by maluoi** [comment]
Hey, sorry for the late reply! I checked your branch, and I kinda get the uneasy feeling that it's getting a bit complicated there? I haven't thought this through super thoroughly yet, but I thought I'd toss up some code to show you kinda what I was thinking about.

This code does pass my test case, but would love to hear your thoughts, I know you've been thinking about this a lot more that I have been! I stuck this over in a feature branch: https://github.com/StereoKit/StereoKit/commit/7b752782db29b1d0d35241d56f49c7c218f789c1

**Comment by austinbhale** [comment]
I agree, it was getting too complicated. I’ve been trying to come up with a solution where Initialize and Shutdown are called automatically, and the steppers are reflected by that in Step. Doing this without locking the entire list gets tricky, since there's no lockless, concurrent access to lists. But if you think Initialize/Shutdown can be called in Step instead of immediately, that makes the problem a lot easier!

My slight concern for this approach is that it should be made aware in the docs that Initialize/Shutdown directly affects the game thread, so there shouldn't be any expensive operations happening there.

Also, if steppers are being produced (added/removed) faster than Step can consume, it gets stuck in an infinite loop. Instead, you could maybe take a snapshot of the queues by calling GetEnumerator (i.e. like foreach does) and dequeue up to the point from where you captured it.

**Comment by austinbhale** [comment]
Oh! Also, maybe have one concurrent queue instead of two separate ones to preserve order. For example, say you have a stepper instance called A:

Let's do the following in under 5ms:

> AddStepper(A)
> AddStepper(A)
> RemoveStepper(A)
> AddStepper(A)

Current behavior:
>Step
> Add(A) -> Initialize(A)
> Add(A) -> Initialize(A)
> Add(A) -> Initialize(A)
> Rem(A) -> Shutdown(A)
>Step

Expected behavior:
>Step
> Add(A) -> Initialize(A)
> Add(A) -> Initialize(A)
> Rem(A) -> Shutdown(A)
> Add(A) -> Initialize(A)
>Step

So I’d recommend one queue with a type of (IStepper, bool) to indicate which state the stepper is in (true: initialize, false: shutdown). Or it could be represented as an enum/long instead of bool.

**Comment by maluoi** [comment]
> But if you think `Initialize`/`Shutdown` can be called in `Step` instead of immediately, that makes the problem a lot easier!

Yeah, I think this approach may actually help clean up the lifetime a bit as well. It's now a lot more clear and specific about when and where `Initialize` and `Shutdown` occur. Previously, `Initialize` could happen on either the sourcethread, or the main thread, depending on whether items were added before or after `SK.Initialize`!

> My slight concern for this approach is that it should be made aware in the docs that Initialize/Shutdown directly affects the game thread, so there shouldn't be any expensive operations happening there.

I think when handing a system like IStepper off to SK, it's fairly intuitive that they're going to be used on the main thread? But I definitely agree that it should be documented explicitly as such! The constructor will still get called from the source thread, so there's still the opportunity to take advantage of that if desired.

> Also, if steppers are being produced (added/removed) faster than Step can consume, it gets stuck in an infinite loop. Instead, you could maybe take a snapshot of the queues by calling GetEnumerator...

As long as steppers are being produced faster than they're being processed, I don't believe there's any solution that can prevent bad things from happening? Even the GetEnumerator trick will not resolve it, it'll just turn into an infinitely growing snowball rather than an infinite loop. A good solution might be to time-box the operations here, and stop after allotted time has run out, but I suspect that may be over-engineering for a problem that doesn't occur in reality?

> So I’d recommend one queue with a type of (IStepper, bool) to indicate which state the stepper is in (true: initialize, false: shutdown). Or it could be represented as an enum/long instead of bool.

This is a _really_ good suggestion, and I did add that to my branch :)

**Comment by austinbhale** [comment]
Sweet, that is clear! Especially with the flexibility of the source thread calling the constructor.

>As long as steppers are being produced faster than they're being processed, I don't believe there's any solution that can prevent bad things from happening? Even the GetEnumerator trick will not resolve it, it'll just turn into an infinitely growing snowball rather than an infinite loop. A good solution might be to time-box the operations here, and stop after allotted time has run out, but I suspect that may be over-engineering for a problem that doesn't occur in reality?

The GetEnumerator/Count trick could work like this (I didn't see your push so I made up var names):
```
int ct = _addRemove.Count;
while (ct-- > 0 && _addRemove.TryDequeue(out (IStepper Stepper, bool Initialize) s))
{
    if (s.Initialize)
    {
        s.Stepper.Initialize();
        _steppers.Add(s.Stepper);
    }
    else
    {
        _steppers.Remove(s.Stepper);
        s.Stepper.Shutdown();
    }
}
```

I'm thinking in the case of longer `Initialize` methods, or maybe they add more steppers in a short burst of a few frames (with `Initialize` taking ~10 ms each), it might be better to step through the Steppers that are currently available rather than hang in `Step`? Like when someone wants to add multiple steppers over the timespan of a few frames, we initialize as much as we can in one frame's snapshot, then save the rest for the next frame. The shutdown procedure would remove all references, without having to initialize/shutdown ones that never got through. Though, I could see the longer loop work too, just want to get that idea out there.

Thanks for looking into this! :)

**Comment by austinbhale** [comment]
On second thought, I think it's pretty clear to try and dequeue all stepper changes instead of grab a snapshot in time. We're basically saying, "for as long as the actions are being enqueued, we guarantee that these steppers will immediately be added/removed for the current or next frame." Instead of a delay-induced visibility. So that logic sounds good to me!

**Comment by maluoi** [comment]
This is now in v0.3.7-preview.8!
