### ISSUE TITLE
Incomplete? Inaccurate? GPU warning

### ISSUE THREAD

**Issue by laultman** [StereoKit/StereoKit#539]
## Description
During debugging in Visual Studio 2022, I have been receiving a distracting warning from SK:
[SK warning] A GPU asset is blocking its thread until the main thread is available, has async code accidentally shifted execution to a different thread since SK.Initialize?

This is a good question. I've been chasing a ghost of sorts all afternoon on this one. If I put a break on a statement just about anywhere in the Initialize or Step methods and the debugger stops the processing. The message shows up in the diagnostics. Naturally, I thought I had committed a grievous mistake in my async stuff. In the process of chasing the ghost all around the code with break statements, I noticed the pattern. The debugger is the other thread that is blocking the GPU.

Maybe add a little heads-up language, "If you are actively debugging in the SK initialize or Step methods, this may be the cause."

## Platform / Environment
Window 11, VS 2022 17.4.2 SK 0.3.6

## Logs or exception details
```
Logs are super helpful, please include them if they're at all relevant!
```
_If you have an exception, details about that would also be essential._

**Comment by maluoi** [comment]
This warning does have potential to be a false positive! It's a bit of a tricky issue to catch as it is, and if I could catch it 100% properly, it probably wouldn't be necessary to have around.

I haven't actually encountered this while debugging, but I guess this might occur if you load an asset and then break before the first frame has happened? Does that sound right? I can probably modify the message to account for this if so.

The condition for this warning [can be found here](https://github.com/StereoKit/StereoKit/blob/64cce81d67fc28f854a8b4f266b9a28515198f47/StereoKitC/asset_types/assets.cpp#L458), and I'll probably have this in until I can implement graphics on a separate thread from the app.

**Comment by laultman** [comment]
I think you are correct in the timing issue. I am loading significant assets during the initialization and am breaking using the debugger during the load. This is related to the "pause" in the Step while loading assets. I am for the most part managing the latency through magician's slight-of-hand distracting the user while it finishes loading and before it gets called for display.
That would entirely explain the GPU warning.
I for one will be extremely happy to have fully async asset loading. If I knew enough about your code I would try to help.
On the updating the message, this may be such an edge case that a pointer to this thread may be sufficient. It would have for me at least.

**Comment by maluoi** [comment]
The biggest bottleneck for loading assets is _usually_ textures, which currently are fully async when used properly. Mesh loading is currently not fully async, but is generally fast enough that it doesn't impact much, unless the mesh is really detailed like extra large photogrammetry.

Can you isolate specifically which assets or asset loading code might be causing the hang? I'd love to know what the root cause is here so it can be focused on. This could either be improper usage of asset data via code before they're fully loaded, or assets that are extra large in file size.

**Comment by laultman** [comment]
I will spend some time over the holidays and diagram out the calls and get you plenty of data. You mentioned textures and photogrammetry. I am providing Azure data driven "hot" loads of glb models created using photogrammetry. Most textures are running between 15 and 30 meg (about 100k poly ea). I may have 50 copies of the same model in the scene. I have tried to figure out how the GPU consumes models to reduce the number of instances on the GPU. It seems to be working, I have stable images. The load is the killer - dead display time. Interestingly, lately the models are drawing 10-20 seconds as ghost images (black/white outlines) with no textures, then display goes away for about 2-3 seconds and reappears with all the textures applied. That is better than no images at all and a blank display.
For contrast, I switched to SK because Unity could never handle the stability of the images. Unity handled the "hot" loads gracefully because I was completely in control of when the display would show an image. In Unity I used a "cheap" stand-in model until the model was available. The downside of Unity hot load was the sequential nature (kind-of) I had to track all the bool-flags which was a complicated process and do it in the loop.
I really like the SK async model loading. It is just the blocking on the main thread. By the way, because of the nature of our platform and the services we provide to customers, we have been able to do a "kind-of" CDN where we are pre-positioning the heavy photogrammetry workload to the edge-remoting computer several minutes in advance of the user needing the asset. This means the load time is only the SSD time to load. That can still be many seconds for large quantities of models. But once loaded it is solid as a rock. The load delay would be totally acceptable if I could have some "loading" thing running while it loads. The issue is the initial load. With SK I don't seem to have any way to know the status of an asset's availability. It is off in never-never-land loading.

**Comment by maluoi** [comment]
Okay, I expect the pause is most likely the photogrammetry meshes! So I'll focus on that for the time being, I don't think you need to worry about the diagram unless there's something else that's choking it up as well.

Since textures were the main bottleneck, I focused all my efforts on making that async first! I haven't actually finished `Mesh`/`Model` async yet, though `Model`s do generally benefit quite a lot from async textures.

Currently, `Tex` has an API for handling their load status, and these, or something similar, will also be added to `Mesh` and `Model` once they have been made completely async. See [`Tex.AssetState`](https://stereokit.net/Pages/StereoKit/Tex/AssetState.html), [`Tex.FallbackOverride`](https://stereokit.net/Pages/StereoKit/Tex/FallbackOverride.html), and `Tex.OnLoaded` (not in the docs yet). You can also find more high level information about loading status over in the [`Assets`](https://stereokit.net/Pages/StereoKit/Assets.html) class!

**Comment by laultman** [comment]
I've spent most of the last couple days trying to fine tune the loads. I have just about squeezed all I can out of the async available to me. I have isolated the pause to the texture loads of the photogrammetry models. I am forcing it to load the assets as early in the app as possible. I've managed to get a "splash screen" inserted and displayed before it takes a pause. At least the user knows something is happening. Loading the models to my assets is not the same as loading them in the GPU. That does not happen, I suppose, until you need to draw them. What causes or when does the GPU to discard a model that has been displayed? You have mentioned somewhere that the GPU keeps models.
