### ISSUE TITLE
Add optional normal direction to Lines / LinePoint

### ISSUE THREAD

**Issue by Jumbli** [StereoKit/StereoKit#559]
## Describe the feature
I like to make the most of Lines.Add to reduce draw calls and help performance. Currently lines always face the user, would it be possible to have an optional Vec3 so we can override the default behaviour and instead pass a fixed direction for the line to face?

## An example use-case
1) Drawing on a white board should have lines that are 2d and not rotated towards the user.
2) We could use Lines.Add as a cheap way to add lots of quads. My initial use of this would be to draw backdrops for text labels (without needing a separate draw call for each).

Thanks.

**Comment by maluoi** [comment]
This is definitely an interesting idea! The camera facing lines are useful, but definitely have some disadvantages to them. I've always been a bit uncertain about how far StereoKit's line rendering API should go, because honestly it's quite a rabbit hole of options.

I would say that right now I have a few obstacles to improving lines:
1. Custom vertex formats (in progress, but kinda tricky).
2. Compute shaders (allows for faster, more flexible calculation of line geometry).
3. Support for multiple line rendering strategies.

3 is the only real blocker here, but 1 and 2 have a big impact on the implementation of 3. I'm a little hesitant to work on this in the near term because of this.

However, it's not too difficult to make a line renderer of your own, especially with the constraints you've mentioned here! And I would recommend it at this stage. I think a specific facing direction may actually be even easier than trying to make a camera facing one. A custom line renderer can also have performance benefits, since you have the option to only update the vertices when the lines change, rather than every frame as SK requires. I had always imagined that an application with robust lines would likely need to make their own system one way or another.

[StereoKit's line renderer](https://github.com/StereoKit/StereoKit/blob/master/StereoKitC/systems/line_drawer.cpp) is actually a pretty high level system in the core, and it's currently less than 200 lines of code as well. It is C code, but should be pretty straightforward to use as reference if you're interested! [The shader](https://github.com/StereoKit/StereoKit/blob/master/StereoKitC/shaders_builtin/shader_builtin_lines.hlsl) is also pretty specific to the line mesh as well. I'd note that a lot of this code is present because it needs to be camera facing, so your own implementation would likely be a decent bit more straightforward!
