### ISSUE TITLE
Fonts get corrupted when over 128 glyphs are used

### ISSUE THREAD

**Issue by Jumbli** [StereoKit/StereoKit#575]
## Description
There seems to be a limit of 128 characters in a font file. If you use more than that, characters start getting corrupted. 

Here is the test code I am using:
```
using StereoKit;

Pose pose = new Pose(V.XYZ(0,0,-1),Quat.FromAngles(0,180,0));

SK.Initialize();

Font f = Font.FromFile("FluentSystemIcons-Filled.ttf");
TextStyle ts = Text.MakeStyle(f,.02f,Color.White);
UI.PushTextStyle(ts);

string icons = "";
int firstIcon = 33;

for (int i=0;i<127;i++) // 127 is fine, but increase this number and you will see some corruptions
{
    Log.Write(LogLevel.Info,"" + i);
    icons += (char)(firstIcon + i);
    if (i%10 == 9)
        icons += " ";
}

SK.Run(()=>{
    UI.WindowBegin("",ref pose, V.XY(.6f,0),UIWin.Body);
    UI.Text(icons);    
    UI.WindowEnd();

});

```

**Comment by maluoi** [comment]
Found it! Should be fixed in the next build :)

One of the lists that tracked glyph UVs recently got switched to a dictionary for faster lookups. SK's dictionaries can be iterated over, but items are not stored contiguously in the array. The code was erroneously using the `count` (valid items) instead of the `capacity` (array size) for iteration. This would lead to a certain number of entries getting skipped when UVs were recalculated for atlas resizing, since valid items would still be beyond the `count` line!

**Comment by maluoi** [comment]
This fix is in now!
