### ISSUE TITLE
Can you make handles optionally respond to the grip button?

### ISSUE THREAD

**Issue by Jumbli** [StereoKit/StereoKit#601]
## Describe the feature
An Oculus recommendation (not a firm requirement, but would likely help get on the official store) is that you should use the grip button to pick up objects. Handles currently use the trigger.
https://developer.oculus.com/resources/vrc-quest-input-2/

In my previous projects I often make both grip and trigger pick up objects. This means that it works well without any user configuration on both the Quest with its well implemented grip button, and the Vive with its horrible grip button where users will naturally favour using the trigger instead.

My ideal solution would be for developers to be able to configure which buttons (trigger / grip) can grab a handle (assuming this is consistent for grabbing windows and sliders) and having the option to use both grip and trigger or just one of them.

A complication is the hand pose. After grabbing something I would expect it to use the pinching pose, regardless if the trigger or grip is used, but when activated in free space and not grabbing something I would like it to use the pointing gesture so it can still be used for hand menus and extending a finger to push buttons. Maybe assigning both buttons as "grabbing" should result in the trigger also making the pointing hand pose so Vive users never have to use the grip button and the only time you see the pinch pose is when you are actively grabbing.

What do you think?

Thanks,

## An example use-case
_How do you imagine this feature being used? What's the context?_

**Comment by maluoi** [comment]
Yeah this is an interesting topic here! Microsoft best practices actually recommend different grab actions for different size objects/affordances. The way we grab things is kinda contextual!

## Grabbing stuff

Picking up small stuff, like a spoon, a pencil, or a sheet of paper is naturally done with the fingertips, maybe 2-3 fingers or so, which maps really well to the pinch gesture. Basically all of SK's UI fits into this size category, which is why I've primarily focused on that so far!

Larger or heavier objects are naturally grabbed with your whole hand, like a bottle, a heavy hardback book, or a backpack. I've definitely had `UI.Handle` representing large objects, and using pinch there can feel pretty weird. This is definitely a case where I'd like to properly support a grip gesture for handles!

A trick here as well, you can add small affordances to large objects to instinctively encourage people to use pinch gestures! And visa versa, adding large affordances will encourage grip gestures from users :)

## Moving forward

I've been wanting to have some settings specifically for `UI.Handle`, allowing for grab, pinch, or both! I think this function in particular really needs to have the flexibility to support different grab gestures. This is relatively easy to add, and if it adds enough value to you on its own, I'd be happy to fast-track this one in before the next update :)

I was working on a big refactor to the interaction system that would have made it a lot easier to configure all of this with a fair bit more granularity! It was a bigger project that I had to shift it to the backburner, and it may take me a bit to get back to it. But that would allow for a lot more customization with respect to sending inputs to the UI! This was basically adding an interactor abstraction between raw inputs and the UI/UX systems, and would allow you to augment SK's default interactors, or replace them entirely. I've been working a lot more with the UI lately, so it's plausible to imagine I may get back to this relatively soon.

**Comment by maluoi** [comment]
This is now in 0.3.7-preview.1570!
