### ISSUE TITLE
Second launch of app on quest pro stays black

### ISSUE THREAD

**Issue by paulmelis** [StereoKit/StereoKit#668]
## Description

Built and deployed the default SK app generated by the sk-maui template to a Quest Pro. The first launch of the app works fine, but after quitting any subsequent launches don't show anything, seems like the app gets stuck in startup. This is with running directly on the Quest, no Link used.

When it comes to Android development I don't really know what I'm doing most of the time, so maybe I'm just screwing things up in the basic workflow. So if there is any better approach/template I'd be happy to try that to see if that fixes this issue.

## Platform / Environment

Quest Pro, SK 0.3.7-preview.1601, VS 17.6.3, Android 12.1 - API32, .net7.0-android33.0

## Logs or exception details

Is there a way to get logging output from an SK app deployed on a Quest?

**Comment by maluoi** [comment]
Currently, I'd recommend using `sk-multi` instead of `sk-maui` for projects. I left `sk-maui` in for the moment just in case, but will likely remove it fairly soon. `sk-maui` has a _lot_ of extra moving parts that I really just found to be unstable to work with. If you could try it again from something `sk-multi` based, that would be helpful!

When you say first/second launch, is this launching from Visual Studio, command line, or via user interaction in the app list? And are you exiting via `SK.Quit`, or via Quest's Quit button from the quick-menu? Quest's button is the more reliable one here right now, and I'm uncertain if having a button that calls `SK.Quit` is even the right pattern to follow for Android apps.

## Logs

For debug logs on Android, Visual Studio's "Output" window in debug mode usually will have the relevant subset of the logs, but for more details you can go directly to `logcat`. It can be pretty important to know about, especially in cases where startup doesn't happen right. `logcat` is a command line tool in the Android SDK that will show you the logs for the whole Android device, and it's typically verbose enough that it needs... filtering.

I haven't actually used it directly by CLI, but dumping `logcat` to a file for browsing in VSCode or something might work pretty well. Alternatively, there's logcat output viewing tools around. I've tried a few, but haven't settled on one since they killed (/Android/Sdk/tools/monitor.bat? doesn't seem to work for me anymore) the one I used to like. Visual Studio technically has one, but it's pretty bad, Android Studio has one that's good, but can be hard to find in their UI.

**Comment by paulmelis** [comment]
Regarding `sk-multi`: ah, I tried that template but got some visual studio errors when opening the generated solution (see below). So I figured that that template was more in flux and not a good base. Steps I did:
```
C:\Users\paulm\Desktop\Projects>mkdir sk-multi-test

C:\Users\paulm\Desktop\Projects>cd sk-multi-test

C:\Users\paulm\Desktop\Projects\sk-multi-test>dotnet new sk-multi
The template "StereoKit: Multitarget project" was created successfully.

Processing post-creation actions...
Restoring C:\Users\paulm\Desktop\Projects\sk-multi-test\sk-multi-test.csproj:
  Determining projects to restore...
  Restored C:\Users\paulm\Desktop\Projects\sk-multi-test\sk-multi-test.csproj (in 159 ms).
Restore succeeded.
Restoring C:\Users\paulm\Desktop\Projects\sk-multi-test\Projects\Android\sk-multi-test_Android.csproj:
  Determining projects to restore...
  Restored C:\Users\paulm\Desktop\Projects\sk-multi-test\Projects\Android\sk-multi-test_Android.csproj (in 42 ms).
Restore succeeded.

C:\Users\paulm\Desktop\Projects\sk-multi-test>dir
 Volume in drive C has no label.
 Volume Serial Number is A482-BF9D

 Directory of C:\Users\paulm\Desktop\Projects\sk-multi-test

14/07/2023  14:17    <DIR>          .
14/07/2023  14:17    <DIR>          ..
14/07/2023  14:17    <DIR>          Assets
14/07/2023  14:17    <DIR>          obj
14/07/2023  14:17    <DIR>          Platforms
14/07/2023  14:17               880 Program.cs
14/07/2023  14:17    <DIR>          Projects
14/07/2023  14:17               718 sk-multi-test.csproj
14/07/2023  14:17             1.776 sk-multi-test.sln
               3 File(s)          3.374 bytes
               6 Dir(s)  16.555.089.920 bytes free

C:\Users\paulm\Desktop\Projects\sk-multi-test>
```

If I then open `sk-multi-test.sln` in VS I get an error dialog saying "One or more projects in the solution were not loaded correctly". More detailed output:

```
C:\Users\paulm\Desktop\Projects\sk-multi-test\Projects\Android\sk_multi_test_Android.csproj : error  : The project file could not be loaded. Could not find file 'C:\Users\paulm\Desktop\Projects\sk-multi-test\Projects\Android\sk_multi_test_Android.csproj'.  C:\Users\paulm\Desktop\Projects\sk-multi-test\Projects\Android\sk_multi_test_Android.csproj

C:\Users\paulm\Desktop\Projects\sk-multi-test\sk_multi_test.csproj : error  : The project file could not be loaded. Could not find file 'C:\Users\paulm\Desktop\Projects\sk-multi-test\sk_multi_test.csproj'.  C:\Users\paulm\Desktop\Projects\sk-multi-test\sk_multi_test.csproj
```

The problems seems to be that the solution looks for `sk_multi_test_Android.csproj` while the file is actually called `sk-multi-test_Android.csproj` (first 2 are hyphens instead of underscores).

> When you say first/second launch, is this launching from Visual Studio, command line, or via user interaction in the app list?

After deploying I launch directly in the Quest from the apps menu. Quiting is using the regular Quest app Quit button, so not an SK call. 

I'll see if I can get logcat to work...

**Comment by paulmelis** [comment]
The hyphens in the directory/project name apparently wreak havoc as even deployment fails (after correcting the names in the solution file). With a new project based on `sk-multi` named `skmultitest` build, deploy and run works, even when quitting an re-running! So no logcat needed and I suspect the issue of not being able to restart an app was something to do with the maui template.

**Comment by maluoi** [comment]
Okay, I'm _really_ glad to hear sk-multi is working better! :D I may just remove maui sooner rather than later.

The dash issue is kinda weird, but I suppose the `sk-multi` name kinda prompts it. That might be a good thing for me to see if I can prevent as well!
