### ISSUE TITLE
Adding a Mesh with KeepData = false to a model,  crash the  Model.RecalculateBoundsExact() most of a time.

### ISSUE THREAD

**Issue by mvvvv** [StereoKit/StereoKit#759]
## Description
Adding a Mesh with KeepData = false to a model,  crash the  Model.RecalculateBoundsExact() most of a time.
Model.RecalculateBounds() doesn't seem to be concerned.

## Platform / Environment
Linux / OpenXR 1.0.20 with the flatscreen simulator / rust binding.

**Comment by maluoi** [comment]
Setting an id that already exists is currently intended to crash. Asset ids should be unique! I don't currently have anything that will alter a non-unique id to be unique, so that's something you'll have to do manually if you're expecting conflicts.

I'll look into `Model.RecalculateBoundsExact`. It won't be able to do an exact calculation without the mesh data, but it probably should _not_ crash there. 😅

**Comment by mvvvv** [comment]
I don't think it's usefull to open a new bug for this but there is a little typo in C# Tex.cs where anisotropy is misspelled 
 as "anisoptropy". This also true in the doc :     /// <'https://stereokit.net/Pages/StereoKit/Tex/Anisoptropy.html'>

**Comment by mvvvv** [comment]
It works well, should I create a new Issue about the anisoPtropie misspelled ?

**Comment by mvvvv** [comment]
It works well, should I create a new Issue about the anisoPtropie misspelled ?
