### ISSUE TITLE
Keyboard Customization API

### ISSUE THREAD

**Issue by maluoi** [StereoKit/StereoKit#831]
## Describe the feature

The new fallback keyboard is designed to be much more customizable! It'll take strings that it can parse into keyboard layouts. StereoKit doesn't necessarily want to fit keyboard layouts for every language in the binary, so having a way to set them up from an external source would be helpful!

This would enable localized keyboards, or custom keyboard designs for more specific use cases.

Should SK have a file format/schema for keyboard layouts? Like a TOML file with a set of layouts for text/numpad/URI that can just be loaded? Or should this just be a function where you can just send in a string, and leave the file format up to the app?

**Comment by LarryAultman** [comment]
I thought about this not just in the KBD context but in a full configuration conceptual model for our platform based on SK. Our team, has experimented with in-house designs and just about every "fad" concept out there.
Our current stance, not-yet-another-markup-language. We literally use JSON because of its universal support. Good/bad or level of effort aside, JSON is acceptable to our customers.

I think I like the idea of a string that the app defines its file format as the most flexible. TOML is aimed at a specific problem that is a very small part of our bag of issues. Devoting time and resources to another library where the issue is less that 1% of our total code load is asking a lot. I have people on my team who's lives revolve around configurations, they get all excited about these things. As the owner, I have a bunch of people on payroll who will never use this or even worry about it.

**Comment by maluoi** [comment]
I'm not a big fan of JSON. It has its uses, but configuration files are not what I would consider a good use for JSON. This is a config file problem, and TOML is a much better fit here.

This would be something implemented at SK's core, and you wouldn't need to add any libraries or even interact with it unless you needed an easy way to configure a custom fallback keyboard (HoloLens 2 will not need a custom keyboard, as it has a full featured one provided by the OS). I'll also probably never have a config file that can't also be done wholly via API as well, so you'd be able to use JSON just fine from top-level if you wanted to.

**Comment by LarryAultman** [comment]
I also am not entirely a fan of JSON either, it's just that customer investment sort of ties our hands in a lot of case. Good to know what you are thinking about. I've seen a considerable number of improvements in the past year in SK. I look forward to the next release.
