### ISSUE TITLE
`Renderer.RenderTo` results in y-inverted image with Android

### ISSUE THREAD

**Issue by austinbhale** [StereoKit/StereoKit#892]
## Description
In v0.3.9, the texture is flipped vertically on Android devices. A quick test can be seen using the RenderCamera tool!

.NET Windows
![image](https://github.com/StereoKit/StereoKit/assets/32556981/d2d660be-9999-4c66-95de-ec0cf785826a)

.NET Android
![IMG_0873](https://github.com/StereoKit/StereoKit/assets/32556981/b1047ad7-17ee-4cdf-9572-9c1416752200)

## Platform / Environment
Correct for D3D (DotNet & UWP projects). GL is probably the culprit (NetAndroid project)

**Comment by maluoi** [comment]
This is a known issue, and very much because of GL, but I haven't really settled on a "correct" fix for it! I've kinda wondered if maybe this could be fixed by flipping the projection matrix in specific cases, or perhaps some GL extension that might be common. I'd be open to suggestions!

In general at the moment, I do something like flip UVs or mesh on Android platforms. When reading color data, I also read it out bottom-to-top as well.

**Comment by austinbhale** [comment]
Ohh I guessed SK standardized top-down textures for retrieving color data. Reading just like GL gives it sounds like less surprises to me :D For this scenario, flipping the projection matrix is perfect, thanks for the tip! Something like:
```
perspectiveMatrix = Matrix.Perspective(fov, (float)_width / _height, 0.01f, 100);
if (Backend.Graphics is BackendGraphics.OpenGL_GLX or BackendGraphics.OpenGL_WGL or BackendGraphics.OpenGLES_EGL)
{
    Matrix flipY = new(
        1, 0, 0, 0,
        0, -1, 0, 0,
        0, 0, 1, 0,
        0, 0, 0, 1
    );
    perspectiveMatrix *= flipY;
}
```
